@startuml

class Variable {
	+String name
	+Type value_type
	+Period period
	+value_type default_value
	+List formula
}

class MyVar {
    +formula(population: Population, period: Period)
}

class Cache {
	+__init__(variable:Variable)
	+set_input(period:Period, value:Variable.value_type)
	+Variable variable
	+Dict[Period, Variable.value_type] value
}

class Period {

}

class Population {
	-Dict[Variable.name, Holder] holders
}

class ImmoCore {
    +Dict[Variable.name, variable] variables
    +load_variables_from_directory(dir_path)
    +load_variables_from_files(file_path)
    +load_variable(variable_class)
}

class Simulation {
    +Population population
}

Variable <|-- MyVar
Cache *-- Variable
Cache -- Period
Population *-- Cache
Simulation *-- Population

@enduml